# Generated by Django 5.2.8 on 2025-11-16 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portatil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=50, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('especificaciones', models.TextField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('mantenimiento', 'Mantenimiento'), ('fuera_servicio', 'Fuera de servicio')], default='disponible', max_length=20)),
                ('sala', models.CharField(max_length=100)),
                ('propietario', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_sala', models.CharField(blank=True, max_length=100)),
                ('a_sala', models.CharField(blank=True, max_length=100)),
                ('de_propietario', models.CharField(blank=True, max_length=100)),
                ('a_propietario', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('portatil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invexia_app.portatil')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.CharField(max_length=100)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='activa', max_length=20)),
                ('portatil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invexia_app.portatil')),
            ],
        ),
    ]
