# Generated by Django 5.2.8 on 2025-11-16 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invexia_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='portatil',
            old_name='marca',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='a_propietario',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='a_sala',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='de_propietario',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='de_sala',
        ),
        migrations.RemoveField(
            model_name='portatil',
            name='especificaciones',
        ),
        migrations.RemoveField(
            model_name='portatil',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='portatil',
            name='numero_serie',
        ),
        migrations.RemoveField(
            model_name='portatil',
            name='propietario',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='duracion',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='nueva_sala',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('RESERVA', 'Reserva'), ('CAMBIO_SALA', 'Cambio de sala'), ('BAJA', 'Baja')], default='GENERAL', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimiento',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portatil',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portatil',
            name='usuario_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portatiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='portatil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='invexia_app.portatil'),
        ),
        migrations.AlterField(
            model_name='portatil',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En uso')], default='DISPONIBLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='portatil',
            name='sala',
            field=models.CharField(default='Almacén', max_length=50),
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
