# Generated by Django 5.2.8 on 2025-11-16 21:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invexia_app', '0002_rename_marca_portatil_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.CharField(choices=[('RRHH', 'Recursos Humanos'), ('IT', 'Tecnología'), ('VENTAS', 'Ventas')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='portatil',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='portatil',
            name='sala',
        ),
        migrations.RemoveField(
            model_name='portatil',
            name='usuario_actual',
        ),
        migrations.AddField(
            model_name='portatil',
            name='almacenamiento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='portatil',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='portatil',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='portatil',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portatil',
            name='pantalla',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='portatil',
            name='procesador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portatil',
            name='ram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='portatil',
            name='sistema_operativo',
            field=models.CharField(blank=True, choices=[('WIN7', 'Windows 7'), ('WIN10', 'Windows 10'), ('WIN11', 'Windows 11'), ('UBUNTU', 'Ubuntu'), ('ARCH', 'Arch Linux'), ('DEBIAN', 'Debian'), ('REDHAT', 'Red Hat'), ('MACOS', 'macOS')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='portatil',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('EN_USO', 'En uso')], default='DISPONIBLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='portatil',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invexia_app.empleado')),
                ('portatil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invexia_app.portatil')),
            ],
        ),
        migrations.DeleteModel(
            name='Movimiento',
        ),
    ]
