# Generated by Django 5.2.6 on 2025-10-14 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('id_dis', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Ordenador', 'Ordenador'), ('Portátil', 'Portátil'), ('Teclado', 'Teclado'), ('Monitor', 'Monitor'), ('Otro', 'Otro')], max_length=20)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('n_serie', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('Funcional', 'Funcional'), ('Averiado', 'Averiado'), ('Obsoleto', 'Obsoleto')], default='Funcional', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Dispositivos',
                'db_table': 'Dispositivos',
            },
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('id_ubi', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Traslados',
            fields=[
                ('id_tras', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_traslado', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.CharField(max_length=100)),
                ('desde', models.IntegerField(blank=True, null=True)),
                ('id_dis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariado.dispositivos')),
                ('id_ubi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventariado.ubicaciones')),
            ],
            options={
                'verbose_name_plural': 'Traslados',
                'db_table': 'Traslados',
            },
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='id_ubi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventariado.ubicaciones'),
        ),
    ]
